- name: Install Node Exporter
  hosts: test-server
  become: true
  vars:
    ne_ver: "1.10.2" 
  tasks:
    - name: Update repos 
      ansible.builtin.apt:
        update_cache: true
      
    - name: Download ne archive
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ ne_ver }}/node_exporter-{{ ne_ver }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ ne_ver }}.linux-amd64.tar.gz"

    - name: Create directory for unzip
      ansible.builtin.file:
        path: /tmp/ne
        state: directory
        mode: '0755'

    - name: Unzip ne
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ ne_ver }}.linux-amd64.tar.gz"
        dest: /tmp/ne
        remote_src: yes
        extra_opts: [--strip-components=1]
    
    - name: Create ne user
      ansible.builtin.user:
        name: node_exporter
        shell: /bin/false
        system: yes
    
    - name: Copy binary file 
      ansible.builtin.copy:
        src: /tmp/ne/node_exporter
        dest: /usr/local/bin/node_exporter
        remote_src: true
    
    - name: Add access
      ansible.builtin.file:
        path: "{{ item }}"
        owner: node_exporter
        group: node_exporter
        mode: '0755'
      loop:
        - /usr/local/bin/node_exporter

    - name: Create ne systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start ne service
      ansible.builtin.systemd:
        name: node_exporter
        state: started
        enabled: yes
        daemon_reload: yes
